import = ["~/.config/alacritty/rose-pine.toml"]
#import = ["~/.config/alacritty/nord.toml"]
[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10

[cursor]
style = "Block"
thickness = 0.2
unfocused_hollow = true
